Website = "https://github.com/Jacalz/wormhole-gui"

[Details]
  Icon = "internal/assets/icon/icon-512.png"
  Name = "wormhole-gui"
  ID = "io.github.jacalz.wormhole_gui"
  Version = "3.0.0"
  Build = 14
